const MoviesTypes = {
  FETCH_TOP_RATED_REQUEST: "FETCH_TOP_RATED_REQUEST",
  FETCH_TOP_RATED_ERROR: "FETCH_TOP_RATED_ERROR",
  FETCH_TOP_RATED_SUCCESS: "FETCH_TOP_RATED_SUCCESS",

  FETCH_NOW_PLAYING_REQUEST: "FETCH_NOW_PLAYING_REQUEST",
  FETCH_NOW_PLAYING_ERROR: "FETCH_NOW_PLAYING_ERROR",
  FETCH_NOW_PLAYING_SUCCESS: "FETCH_NOW_PLAYING_SUCCESS",

  FETCH_UPCOMING_REQUEST: "FETCH_UPCOMING_REQUEST",
  FETCH_UPCOMING_ERROR: "FETCH_UPCOMING_ERROR",
  FETCH_UPCOMING_SUCCESS: "FETCH_UPCOMING_SUCCESS",

  FETCH_RANDOM_REQUEST: "FETCH_RANDOM_REQUEST",
  FETCH_RANDOM_ERROR: "FETCH_RANDOM_ERROR",
  FETCH_RANDOM_SUCCESS: "FETCH_RANDOM_SUCCESS",

  FETCH_MOVIE_DETAILS_REQUEST: "FETCH_MOVIE_DETAILS_REQUEST",
  FETCH_MOVIE_DETAILS_ERROR: "FETCH_MOVIE_DETAILS_ERROR",
  FETCH_MOVIE_DETAILS_SUCCESS: "FETCH_MOVIE_DETAILS_SUCCESS",

  FETCH_MOVIE_TRAILERS_REQUEST: "FETCH_MOVIE_TRAILERS_REQUEST",
  FETCH_MOVIE_TRAILERS_ERROR: "FETCH_MOVIE_TRAILERS_ERROR",
  FETCH_MOVIE_TRAILERS_SUCCESS: "FETCH_MOVIE_TRAILERS_SUCCESS",

  FETCH_COMMENTS_REQUEST: "FETCH_COMMENTS_REQUEST",
  FETCH_COMMENTS_ERROR: "FETCH_COMMENTS_ERROR",
  FETCH_COMMENTS_SUCCESS: "FETCH_COMMENTS_SUCCESS",

  ADD_COMMENT: "ADD_COMMENT",
  REMOVE_COMMENT: "REMOVE_COMMENT",
  COMMENT_UPDATING: "COMMENT_UPDATING",
  COMMENT_UPDATING_ERROR: "COMMENT_UPDATING_ERROR",

  FETCH_LIKES_REQUEST: "FETCH_LIKES_REQUEST",
  FETCH_LIKES_ERROR: "FETCH_LIKES_ERROR",
  FETCH_LIKES_SUCCESS: "FETCH_LIKES_SUCCESS",

  ADD_LIKE: "ADD_LIKE",
  REMOVE_LIKE: "REMOVE_LIKE",
  LIKE_UPDATING: "LIKE_UPDATING",
  LIKE_UPDATING_ERROR: "LIKE_UPDATING_ERROR",

  FETCH_DISLIKES_REQUEST: "FETCH_DISLIKES_REQUEST",
  FETCH_DISLIKES_ERROR: "FETCH_DISLIKES_ERROR",
  FETCH_DISLIKES_SUCCESS: "FETCH_DISLIKES_SUCCESS",

  ADD_DISLIKE: "ADD_DISLIKE",
  REMOVE_DISLIKE: "REMOVE_DISLIKE",
  DISLIKE_UPDATING: "DISLIKE_UPDATING",
  DISLIKE_UPDATING_ERROR: "DISLIKE_UPDATING_ERROR",

  FETCH_FAVOURITES_REQUEST: "FETCH_FAVOURITES_REQUEST",
  FETCH_FAVOURITES_ERROR: "FETCH_FAVOURITES_ERROR",
  FETCH_FAVOURITES_SUCCESS: "FETCH_FAVOURITES_SUCCESS",

  ADD_FAVOURITE: "ADD_FAVOURITE",
  REMOVE_FAVOURITE: "REMOVE_FAVOURITE",
  FAVOURITE_UPDATING: "FAVOURITE_UPDATING",
  FAVOURITE_UPDATING_ERROR: "FAVOURITE_UPDATING_ERROR",
};

export default MoviesTypes;
