const UserTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERROR: "REGISTER_ERROR",

  FORGOT_PASS_REQUEST: "FORGOT_PASS_REQUEST",
  FORGOT_PASS_SUCCESS: "FORGOT_PASS_SUCCESS",
  FORGOT_PASS_ERROR: "FORGOT_PASS_ERROR",

  RESET_PASS_REQUEST: "RESET_PASS_REQUEST",
  RESET_PASS_SUCCESS: "RESET_PASS_SUCCESS",
  RESET_PASS_ERROR: "RESET_PASS_ERROR",

  UPDATE_PASS_REQUEST: "UPDATE_PASS_REQUEST",
  UPDATE_PASS_SUCCESS: "UPDATE_PASS_SUCCESS",
  UPDATE_PASS_ERROR: "UPDATE_PASS_ERROR",

  UPDATE_CONTACT_REQUEST: "UPDATE_CONTACT_REQUEST",
  UPDATE_CONTACT_SUCCESS: "UPDATE_CONTACT_SUCCESS",
  UPDATE_CONTACT_ERROR: "UPDATE_CONTACT_ERROR",

  DEACTIVATE_ACCOUNT_REQUEST: "DEACTIVATE_ACCOUNT_REQUEST",
  DEACTIVATE_ACCOUNT_SUCCESS: "DEACTIVATE_ACCOUNT_SUCCESS",
  DEACTIVATE_ACCOUNT_ERROR: "DEACTIVATE_ACCOUNT_ERROR",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_ERROR: "LOGOUT_ERROR",

  RESET_MESSAGES: "RESET_MESSAGES",
};

export default UserTypes;
